### PR TITLE
Terraform 0.14 upgrade

### PR DESCRIPTION
**Pull request by maximmi**
## what
- Upgrade to support Terraform 0.14 and null-label 0.24.1 and bring up to current Cloud Posse standard

## why
- Support Terraform 0.14
- Standardize Cloud Posse Terraform modules

### CODE REVIEW

**Comment by xophere** [comment]
Need this.

**Comment by xophere** [comment]
This lack of TF .14 is holding our whole code base back.  If this isn't going to be approved we need to implement a few of our modules with a different base.  Is there anything we could do to help this progress?  Is there an issue with this module that is preventing it getting reviewed?  Should we not expect it to be able to track the more core modules?

**Comment by Nuru** [comment]
/test all

Sorry, @xophere , we have close to 200 Terraform modules that need updating and it takes us time to update them all. We are working toward automating some of the updates so hopefully this will go much faster in the future. In this case, there were a chain of modules this module uses that all had to be updated first, so this module took longer than most to get upgraded.

**Review by Nuru — APPROVED** [review]

**Pull request merged**
