### PR TITLE
expose s3 lifecycle options

### PR DESCRIPTION
**Pull request by deadlysyn**
## what
* expose s3 lifecycle options for access logs

## why
* be consistent across alb/nlb modules

## references
* https://github.com/cloudposse/terraform-aws-alb/pull/44

### CODE REVIEW

**Comment by deadlysyn** [comment]
@jamengual 👀

**Comment by jamengual** [comment]
@deadlysyn looks like is failing the test, I think you need to give a default to the `health_check_threshold` variable

**Comment by deadlysyn** [comment]
sorry about that, i forgot to commit the updated fixtures. i was hitting an issue on the initial repo checkup where tests wouldn't pass due to that timeout variable. i cleaned that up, since from reading https://www.terraform.io/docs/providers/aws/r/lb_target_group.html#timeout a custom value cannot be set for NLB.

this should just get the tests running as-is... 🤞 i didn't commit because i have some parallel work relating to the bucket encryption which includes new tests so didn't push anything test-related. sorry about that!

**Comment by jamengual** [comment]
we got another test error : 
```

TestExamplesComplete 2020-07-10T18:39:39Z command.go:121: module.nlb.aws_lb_target_group.default: Creating...
TestExamplesComplete 2020-07-10T18:39:39Z command.go:121: 
TestExamplesComplete 2020-07-10T18:39:39Z command.go:121: Error: Error creating LB Target Group: ValidationError: Health check interval '15' not supported for target groups with the TCP protocol. Must be one of the following values '[10, 30]'.```

can you push a fix ?

**Comment by jamengual** [comment]
@deadlysyn

**Comment by deadlysyn** [comment]
standby fixing a test issue...

**Comment by deadlysyn** [comment]
@jamengual tests run locally...

**Pull request merged**
