### PR TITLE
Add environment variable for null-label

### PR DESCRIPTION
**Pull request by okgolove**
## what
* Use environment variable for null-label module

## why
* Unifying null-label usage across modules

### CODE REVIEW

**Comment by adamantike** [comment]
Bump! Is there any chance this can be reviewed?

**Review by aknysh — APPROVED** [review]

**Comment by adamantike** [comment]
Thank you!

**Comment by Nuru** [comment]
@aknysh This should have been updated/converted to `context.tf`/`null-label` v0.19.2 instead. OK for now, but if this comes up in other modules, please insist on the conversion.

**Pull request merged**
